---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keel
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: authelia-authelia@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - sigkill.taptappers.club
      secretName: sigkill-tls
  rules:
    - host: sigkill.taptappers.club
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keel
                port:
                  number: 9300
