---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: velero-ui
  namespace: velero
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: authelia-authelia@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - backup.taptappers.club
      secretName: backup-tls
  rules:
    - host: backup.taptappers.club
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: velero-ui
                port:
                  number: 3000
