---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authelia

resources:
  - namespace.yaml
  - configmap.yaml
  # secrets are managed by ansible (synced from Bitwarden)
  # - authelia-secrets
  # - authelia-users
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - middleware.yaml
