---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webtrees
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: authelia-authelia@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: webtrees.taptappers.club
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webtrees
            port:
              number: 80
  tls:
  - hosts:
    - webtrees.taptappers.club
    secretName: webtrees-tls-secret
