---
# Daily restart to pull latest content from git
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hugo-site-refresh
  namespace: sites
spec:
  # Run daily at 5 AM IST (23:30 UTC) - after backups complete
  schedule: "30 23 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: hugo-deployer
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  kubectl rollout restart deployment/hugo-site -n sites
          restartPolicy: OnFailure
