---
apiVersion: v1
kind: Service
metadata:
  name: firefly
  namespace: apps
  labels:
    app: firefly
spec:
  selector:
    app: firefly
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
